### ISSUE TITLE
Content negotiation

### ISSUE THREAD

**Issue by penibelst** [gjtorikian/html-proofer#108]
Proofer should emulate [content negotiation](http://httpd.apache.org/docs/current/content-negotiation.html) for html files. We could try to do it like Apache’s `MultiViews`:

> The effect of `MultiViews` is as follows: if the server receives a request for `/some/dir/foo`, if `/some/dir` has MultiViews enabled, and `/some/dir/foo` does not exist, then the server reads the directory looking for files named `foo.*`, and effectively fakes up a type map which names all those files, assigning them the same media types and content-encodings it would have if the client had asked for one of them by name. It then chooses the best match to the client's requirements.

Saying this I think it’s time for an own `Internal` class that fakes all the server things we support: `DirectoryIndex`, `MultiViews`, `followlocation`, hashes, etc.

``` ruby
uri = Proofer::Internal.new("path/to/internal/ressource", options = {})

if uri.invalid? do
  if uri.hash? do
    issues << "Hash not found"
  elsif uri.empty?
    issues << "Uri empty"
  elsif uri.ugly?
    issues << "Uri ugly"
  end
end
```

**Comment by willnorris** [comment]
:+1: Now that Jekyll 3 is going to have good support for extensionless URLs (which will map to *.html files on disk), having html-proofer emulate content negotiation would be really helpful for being able to test sites using this URL style.

**Comment by fulldecent** [comment]
I do not think server emulation belongs in this project (see project scope, not approved, #422).

GitHub pages uses magic, Apaches uses htaccess, and other servers use god-knows-what. Knowledge of these systems does not belong in this project.

Here is a way to accomplish what this issue is requesting:

1. Spin up a server to host the HTML
2. Use html-proofer with URL swap to point local files to that server (probably localhost:8888)

Perhaps someone could use this approach with a full, minimally viable example and publish it here so that we may add it to a wiki. This solves the problem, respects project scope and helps people with the same issue.

**Comment by fulldecent** [comment]
Related issue #427

**Comment by fulldecent** [comment]
We have now opened a project wiki and this would be a great topic to add.

If anyone wants to help with the documentation per above I will be happy to review and help get it into the wiki.

Closing issue for now. But please continue to discuss if you are interested in contributing.
