### ISSUE TITLE
Do not check for favicon link on Redirect pages

### ISSUE THREAD

**Issue by eksperimental** [gjtorikian/html-proofer#191]
I have raised an issue in the jekyll-rediret-from plugin project
https://github.com/jekyll/jekyll-redirect-from/issues/63
regarding html-proof checking for the favicon link,
and a valid point is that those pages are not meant to be bookmarked, or visutalized for longer than a few seconds, or miliseconds in some cases,
so I think i wouldn't be a bad idea that the app doesn't complain about the favicon link missing if it's a pragma redirect page.

what do you guys think?

**Comment by gjtorikian** [comment]
One can simply ignore the file with [`file_ignore`](https://github.com/gjtorikian/html-proofer/blob/14edbcaaee5dc078f1d4c7ae938e553174741ba7/spec/html/proofer_spec.rb#L78). I think it would be incredibly difficult to parse out from a file what is or is not a redirect page. Proofer would need to open ever file and check the `meta` tag to see if it is redirected or not. It's far easier for a human to just ignore the redirect files since, as you say, they're around for only a few moments.

**Comment by eksperimental** [comment]
but aren't you reading the page to diagnose that there no favicon link in the first place?

**Comment by gjtorikian** [comment]
Sure, we're reading the page to check for a favicon. But to add a "check for `meta` tag, and if it exists, ignore the missing favicon" step to the process would slow the checks down. And adding a special `--skip-favicon-for-redirect`s flags seems heavy-handed.

**Comment by eksperimental** [comment]
I see. no worries, I'm working on a bash script to weed out errors like these ones... 
So you can still use it in CI.
I will share the link when published

**Comment by gjtorikian** [comment]
:cool:
