### ISSUE TITLE
Is there an argument in order to ignore empty mailto?

### ISSUE THREAD

**Issue by PanosSakkos** [gjtorikian/html-proofer#271]
Hey!

I have the following href:

````
href="mailto:?subject={{page.title}}&body={{site.url}}{{site.baseurl}}{{page.url}}"
````

Which breaks the build. 
Is there any way to bypass this mailto rule?

Thanks!
:panos

**Comment by gjtorikian** [comment]
For this specific link, you could add [the `data-proofer-ignore`](https://github.com/gjtorikian/html-proofer#ignoring-content) attribute to the element. Since the link is dynamically generated (based on the Liquid tags), the only other solution of `href_ignore` would be less than ideal, since it only works on Strings and Regular Expressions. If you wanted to go that route, you could make the ignore rule a regular expression that reads something like `/^mailto:\?subject=/`. Hope that helps!

**Comment by PanosSakkos** [comment]
Worked like a charm! :wink:
