### ISSUE TITLE
HTML pretty links & extensions

### ISSUE THREAD

**Issue by Floppy** [gjtorikian/html-proofer#309]
I'm using html-proofer with Jekyll, and both Jekyll's built-in web server and github pages will serve `/example.html` as `/example`, to make the links prettier. However, because html-proofer operates on the files, not using a server with that ability, I have to include `.html` in my links to make it pass. Is there a way, or could there *be* a way, to get html-proofer to check an .html extension if there wasn't one specified? This would of course have to be non-default behaviour, otherwise it could be glossing over broken links if the server *wasn't* doing that job.

**Comment by wjdp** [comment]
Jekyll will make `/example/index.html` for a pretty URL of `/example/`. You're linking to `/example` which the GH pages/Jekyll internal webserver will redirect to `/example/` (the correct URL as it's a directory),

When you link to a directory as a file (`/example` over `/example/`) two requests have to be made, the first request `/example` returns a redirect (301 or 302) to `/example/`. This is seen as bad practice as this additional request slows navigation of your site.

The fix is to turn all your `/example` links to `/example/`. html-proofer is happy with these linls.

**Comment by Floppy** [comment]
But, Jekyll isn't generating those. I've not got pretty links set up for every page (I don't think there's a way to do it globally?), as the servers I'm using do that happily for me without configuration. That means that on disk (where html-proofer looks), it's still `/example.html` which I can refer to as `\example` in my links. Does that make sense?

This might just be my problem, of course, it was just a thought :)

**Comment by Floppy** [comment]
Looks like @parkr has worked on support for this in https://github.com/gjtorikian/html-proofer/pull/221, but it never made it in?

**Comment by Floppy** [comment]
Having tried a few different ways, I don't think Jekyll 3 sites are testable with this at the moment, because page URLs generated in links, etc, no longer include the extension. I'll try to fork this and ressurect @parkr's PR, see how far I get.

**Comment by Floppy** [comment]
See #311 for an active PR which allows this. You can use it in your projects by specifying the repo and branch in your gemfiles:

```
gem 'html-proofer', github: "Floppy/html-proofer", branch: "jekyll-3-extensionless-links"
```
