### ISSUE TITLE
Add entries to cache if script is killed early

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#405]
Checking links takes a long time. This could easily exceed the Travis's 10-minute limit when it kills the script. Users are also likely to press <kbd>Ctrl</kbd>-<kbd>C</kbd> if they get bored.

html-proofer has an option to save checked links to cache ("LinkCheck" with `--timeframe`). But if html-proofer is killed while checking links then all completed checks will NOT be saved to cache.

We should store each link check to cache immediately. Then if a run is interrupted the second invocation will resume where the first left off.

**Comment by fulldecent** [comment]
Better yet, we could store to the cache immediately after every successful link check. Updating cache is much less expensive than network access.

**Comment by gjtorikian** [comment]
Having completely redone the cache in [the next major upgrade for HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) this is close to impossible to do. Well, not impossible, but rather, switching one problem for another.

If the cache is written to as links are found, it would slow down the validation, because we would have to write to disk on every URL response. So you're not really "saving" much time. If performance is an issue (if it takes > 10 minutes to run proofer), then that's certainly an issue to look into.
