### ISSUE TITLE
False error on escaped internal hash references

### ISSUE THREAD

**Issue by xu-cheng** [gjtorikian/html-proofer#482]
Sometimes, the internal hash references for `<a href="">` have to be escaped to be accepted by jQuery (Ref: https://api.jquery.com/jQuery.escapeSelector/). As a result, the internal hash references in the `href` will be slightly different than the one in the element. This will cause html-proofer reporting a false error.

A minimal example to reproduce the problem
```html
<!DOCTYPE HTML>
<html lang="en">
<body>
<div id="some:id">element</div>
<a href="#some\:id">a link</a>
</body>
</html>
```

The html-proofer will report:
```
  *  linking to internal hash #some\:id that does not exist (line 5)
     <a href="#some%5C:id">a link</a>
```

**Comment by gjtorikian** [comment]
Thank you for the explanation. I'm not sure I can support this. Using your test file, the browser itself doesn't head to that `div` when clicking on the link. And it's risky to simply ignore any escaped character (`\:`) because it's more likely the result of a human error.

For something like this you can do `swap_urls` to create a regexp that rewrites the link, eg: `swap_urls: { /^#(.+?)\\:(.+)/ => "\1\2"}`
