### ISSUE TITLE
error after moving from 3.11.1 to 3.15.3

### ISSUE THREAD

**Issue by jaxxzer** [gjtorikian/html-proofer#562]
We are using html-proofer in travis ci for [this project](https://github.com/bluerobotics/bluerobotics.github.io/commits/master). The project failed when it installed 3.15.3, and is passing again after rolling it back to 3.11.1. I'm not sure what the problem is.

failing: https://github.com/bluerobotics/bluerobotics.github.io/commit/ddee1bb97060990aa6de0b5b48c138e8001a76df
passing: https://github.com/bluerobotics/bluerobotics.github.io/commit/9d7e2f4b45035a3a6cc209503e54815e869244aa

**Comment by jaxxzer** [comment]
and build log for the failure: https://travis-ci.org/github/bluerobotics/bluerobotics.github.io/builds/680705738

**Comment by gjtorikian** [comment]
Hi, this error is due to the `&.`, which was added to Ruby in 2.3. According to the logs, you are running Ruby 2.2.

Ruby 2.2 and 2.3 have become end-of-lifed. I _very aggressively_ target the newest versions to ensure up-to-date security fixes.I recommend upgrading to Ruby 2.5--Ruby 2.4 was end of lifed at the end of March.
