### ISSUE TITLE
Link checking failed with "441 No error"

### ISSUE THREAD

**Issue by SkypLabs** [gjtorikian/html-proofer#584]
Hi,

I use HTMLProofer to check the output of Jekyll for my personal website. I recently encounter a quite surprising error message when testing an external link:

```
- ./_site/support/index.html
  *  External link https://www.buymeacoffee.com/skyplabs failed: 441 No error
```

You can see the full log messages here (v3.16.0): https://travis-ci.org/github/SkypLabs/blog.skyplabs.net/builds/726953872

Any idea why?

Thank you in advance.

**Comment by gjtorikian** [comment]
`441` is a non-standard error code—it seems like something `buymeacoffee.com` has made up. This could be because they've flagged the User Agent as something to block (https://github.com/gjtorikian/html-proofer/issues/215).

I would suggest changing the User Agent, or using `http_status_ignore` to ignore this number.

**Comment by SkypLabs** [comment]
It's exactly this non-standard error code which surprised me and I thought it might be a software issue. I didn't think about checking the status code returned by `buymeacoffee.com` with the default user agent of HTMLProofer. My bad.

I made HTMLProofer ignore this status code :+1: 

Thank you for your help.
