### ISSUE TITLE
Bad behavior with file_ignore

### ISSUE THREAD

**Issue by mazzystr** [gjtorikian/html-proofer#588]
I'm using the following option with file ignore... `:file_ignore        => [ /^((?!(abc)).)*$/, /^((?!(def)).)*$/ ]`
When I run htmlproofer I get ....
```
Checks html files for broken external links ...
{:assume_extension=>true, :log_level=>:info, :file_ignore=>[/^((?!abc).)*$/, /^((?!def).)*$/], :external_only=>true, :http_status_ignore=>[429, 999]}
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...
Checking 0 external links...
Ran on 0 files!
HTML-Proofer finished successfully.
Checks html files for broken internal links ...
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...
Ran on 0 files!
HTML-Proofer finished successfully.
```

If I adjust the option to ... `:file_ignore        => [ /^((?!(abc|def)).)*$/ ]`
I get...
```
Checks html files for broken external links ...
{:assume_extension=>true, :log_level=>:info, :file_ignore=>[/^((?!(abc|def)).)*$/], :external_only=>true, :http_status_ignore=>[429, 999]}
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...
Checking 37 external links...
Ran on 2 files!
- ./_site/abc/index.html
  *  External link https://example.io/blah/broken/#blah failed: 404 No error
rake aborted!
HTML-Proofer found 1 failure!
```
if I fix the link and run again...
```
Checks html files for broken external links ...
{:assume_extension=>true, :log_level=>:info, :file_ignore=>[/^((?!(abc|def)).)*$/], :external_only=>true, :http_status_ignore=>[429, 999]}
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...
Checking 37 external links...
Ran on 2 files!
- ./_site/def/index.html
  *  External link https://example.io/blah/broken/#blah failed: 404 No error
rake aborted!
HTML-Proofer found 1 failure!
```

Do you have any suggestions to capturing all the errors in all found files in one run?

This bug is regarding trying to the functionality in [ignoring-new-files](https://github.com/gjtorikian/html-proofer#ignoring-new-files) to work

**Comment by gjtorikian** [comment]
I worry this has nothing to do with `file_ignore` and has to do with the URL checker itself. Could you remove that option and report back on what happens?

**Comment by riccardoporreca** [comment]
@mazzystr, I guess you have an issue with your overly complicated regex and the logic behind its application.

I looks like you are trying to exclude the generated `./_site/abc/index.html` and `./_site/def/index.html` from the check on the external links. However, you use a negative lookahead `?=` which goes against that since this are regex' for `file_ignore`, so they should match what you want to ignore.

In your first case, with `:file_ignore => [ /^((?!(abc)).)*$/, /^((?!(def)).)*$/ ]` you are excluding any file that (does not start with `abc`) **OR** (does not start with `def`), which of course means you are excluding all files (look it the opposite way, there is no string that starts with `abc` **AND** starts with `def`).
The log statement `Ran on 0 files!` is confirming that.

When you use `:file_ignore => [ /^((?!(abc|def)).)*$/ ]`, you exclude any file which (does not start with (`abc` **OR** `def`)), which is quite different. This is basically not the correct the way to combine the two regex into one.
In fact this means you are running the test only for the two `abc` and `def` pages, as confirmed by `Ran on 2 files!`.
It is misleading that only one of the file names is logged when reporting the broken link (perhaps HTMLProofer only logs one of them since the link is the same, @gjtorikian?). When you run it the second time, it probably just only finds the broken link in the `def` file and reports that file.

Btw, you can see your regex in actions at https://rubular.com/r/An7IrxXLuJ9c4q

In any case, you don't need any look-ahead or even to match the whole string with your regex, which can be way simpler. if my assumption is right about your intention, you can get along with much simpler equivalent alternatives of `file_ignore` (which also matche the directory separator `/`)
```rb
:file_ignore => [ /^abc\//, /^def\// ]
:file_ignore => [ /^(abc|def)\// ]
```
otherwise if you really want to exclude all otherfiles, the simplified `:file_ignore => [ /^(?!(abc|def)\/)/ ]` would probably do.

On a side note, that the example described in [Ignoring new files](https://github.com/gjtorikian/html-proofer#ignoring-new-files) uses `url_ignore` to avoid checking links **_to_** new files, whereas you seem to exclude files from being checked for their content via `file_ignore`.

**Comment by gjtorikian** [comment]
Unsure if this is still an issue given the last comment, please reopen otherwise.
