### ISSUE TITLE
I still experience the issue #607 with release 3.18.1

### ISSUE THREAD

**Issue by MrSeccubus** [gjtorikian/html-proofer#611]
Here's a tarbar of the site
[site.zip](https://github.com/gjtorikian/html-proofer/files/5707723/site.zip)

**Comment by MrSeccubus** [comment]
This is the original issues where internal hashref's are not recognized.

**Comment by gjtorikian** [comment]
Ack, sorry about that. When #612 is merged, 3.18.2 should fix it.

**Comment by gjtorikian** [comment]
It took me a very long time to figure out but at the top of your page is the following code:

```html
    <base href="/">
```

So the link to `#content` results in an error saying that `content` cannot be found, even though `id="content"` exists.

However, html-proofer is working as expected. According to [the documentation for `<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#In-page_anchors), the value here is prepended to every link, even hashes. Thus the final link that html-proofer sees is `/#content`, which doesn't exist.

You will need to remove the `base` tag, or rewrite it in such a way so that it correctly points to the same file it's in.
