### ISSUE TITLE
Removal of --check-html

### ISSUE THREAD

**Issue by tbm** [gjtorikian/html-proofer#722]
The release of 4.0 broke my CI because the `--check-html` option was removed.

I don't see anything about the removal in the changelog.

I found commit 75d786c096 "Remove HTML parsing feature" which has no explanation why this feature was removed.

I am probably not the only user who relied on `--check-html`.

Why was this removed? Can it be restored, or is there an alternative software that performs this function?

**Comment by gjtorikian** [comment]
This was intentionally removed as part of the html-proofer 4.0 major release. It was removed because, over the years, it has provided more false positives than actual errors. HTML 5 engines in particular are much more forgiving of broken HTML, and so it logging the four or five small errors this check actual looked for was not worth the trouble of maintainence (I'm just one developer).

I know of no other tools which duplicate the feature but there might be some W3C validators which run a similar check.

**Comment by tbm** [comment]
Thanks for your explanation.  I'm sad this feature was removed (as I found it useful) but I understand.

I think this needs to be prominently documented in the changelog, though.

Also, I wonder if `--check-html` should be a no-op so it doesn't break existing scripts. (Or maybe it should print a warning that the option was removed.)   But maybe this is a bad idea.  I'm not sure.

**Comment by gjtorikian** [comment]
Good call. https://github.com/gjtorikian/html-proofer/pull/674 was added to the changelog, but I just realized that was wiped away by the changelog script. 

https://github.com/gjtorikian/html-proofer/blob/93ba616eb45b7ba844197fc29824995e8fcd2279/UPGRADING.md now exists as a document for all the breaking changes between 3 and 4.

**Comment by tbm** [comment]
That document looks great!  Thanks so much.

**Comment by Seirdy** [comment]
Sad to see this go, but I understand why it went. Personally, I think that the two best alternatives are the [Nu HTML Checker](https://github.com/validator/validator) (for HTML, CSS, and SVG validity) and libxml's [xmlint](https://manpages.debian.org/buster/libxml2-utils/xmllint.1.en.html) (for syntactical well-formedness, e.g. remembering optional closing tags).

Personally: I don't think it's always a good idea to lean heavily upon spec-compliant error-recovery and implied closing tags. They can have a perf overhead in very long pages; for example, some Wikipedia articles have thousands of DOM nodes and would be noticeably slower to render on low-end hardware if their markup was more lax than it already is.

Moreover, some non-browser clients don't implement the full spec. For instance, I've seen Bing get tripped up by implicit `<head>` and `<body>` tags; since Bing powers nearly every alternative search engine (DDG, Yahoo, etc), this was quite noticeable.
