### ISSUE TITLE
Link checker triggered for href=""

### ISSUE THREAD

**Issue by ppipelin** [gjtorikian/html-proofer#746]
Hello, 
I think this may be a unwanted behaviour: the link checker triggers the error `'a' tag is missing a reference` even for for tags that have `href=""` (going back to root)?
Thanks

**Comment by gjtorikian** [comment]
By default, this is the case. As [the docs](https://github.com/gjtorikian/html-proofer#configuration) say:

> In HTML5, this is technically allowed, but could also be human error.

That is to say, it's more "dangerous" for someone to forget to put an `href` attribute, rather than allow blank references to go through. By default, html-proofer will raise this as an error, but you can disable it by passing `allow_missing_href = true` in the configuration.
