### ISSUE TITLE
Test suite depends on vcr, which is not free software

### ISSUE THREAD

**Issue by Apteryks** [gjtorikian/html-proofer#786]
Hello,

The test suite depends on vcr, which due to its Hippocratic license, is not considered free and cannot be included in FSDG-compliant distributions (see this bug in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984689).

I had to disable the test suite of html-proofer in GNU Guix because of that.

Thanks!

**Comment by gjtorikian** [comment]
It seems that since version 6, the gem is dual-licensed under MIT _and_ Hippocratic: https://github.com/vcr/vcr/blob/84e5040c3ba67a80d715773f0228a8e31541af1c/vcr.gemspec#L16

Would upgrading to v6 here help you?

**Comment by Apteryks** [comment]
Hi!

 It's not dual-licensed (that would defeat the point of the Hippocratic license); rather, the files contributed as MIT until the project switched license remain MIT, while the new files (and the whole) is covered by the Hippocratic license [0].

[0]  https://github.com/vcr/vcr/issues/804

**Comment by gjtorikian** [comment]
Are there any license compliant gems that do the same thing VCR does? I don’t mind replacing it with a new library but I’m struggling to find a solution here.

**Comment by Apteryks** [comment]
If there's nothing else available we could try to use the older 5.0.18 version on commit g842b2bf, the last commit before the license switch (git describe: v5.0.0-18-g842b2bf).

**Comment by gjtorikian** [comment]
Well, html-proofer is locked and working with `~> 2.9`, which is well below the version licensing change in 5.1.

I'm closing this out because I think I'm in compliance, but feel free to reopen/comment if I'm misunderstanding. Again, my understanding is that because this gem uses VCR 2.9.3, which is MIT licensed, that it is in compliance.

**Comment by Apteryks** [comment]
Indeed, it's currently in compliance.  Something to keep in mind for the future though.  Cheers!

**Comment by gjtorikian** [comment]
> Indeed, it's currently in compliance. Something to keep in mind for the future though.

As long as we’re giving unsolicited advice: perhaps Debian should try to work harder to give open source maintainers help in solving problems that affect their project, rather than go around raising false warnings. Instead of a project maintainer going around looking for dependencies that have licenses that fit Debian’s needs, Debian maintainers should go out and help the packages in question, or build their own alternatives.
